name: Auto Merge PR

on:
  pull_request_target:
    types: [labeled]

jobs:
  auto-merge:
    name: Auto Merge
    runs-on: ubuntu-latest
    if: github.event.label.name == 'validation passed'
    steps:
      - uses: actions/checkout@v4

      - name: Enable auto-merge
        run: gh pr merge ${{ github.event.pull_request.html_url }} --auto --merge
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} 