name: Auto Merge Validated PRs

on:
  schedule:
    - cron: '*/10 * * * *'  # Run every 10 minutes
  workflow_dispatch:  # Allow manual trigger

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup GitHub CLI
        run: |
          gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"
      
      - name: Auto Merge PRs
        run: |
          # Get all open PRs with "validation passed" label
          prs=$(gh pr list --label "validation passed" --json number,url --jq '.[].url')
          
          # Loop through each PR and attempt to merge
          if [ ! -z "$prs" ]; then
            echo "$prs" | while read pr; do
              if [ ! -z "$pr" ]; then
                echo "Attempting to merge PR: $pr"
                gh pr merge "$pr" --auto --merge --delete-branch || true
              fi
            done
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 