name: Chore

on:
  push:
    branches: [ main ]

jobs:
  Format:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Run format script
      run: python3 scripts/format.py

  Update_Data:
    runs-on: ubuntu-latest

    steps:      
    - name: Run data merge script
      run: python3 scripts/data.py
      
    - name: Commit changes if any
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add data/all-records.json
        git commit -m "chore: Update all-records.json" || echo "No changes to commit"
        git push
