name: Close issue/PR on adding invalid label

on:
  issues:
    types: [labeled]
  pull_request_target:
    types: [labeled]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  close-on-adding-invalid-label:
    if: github.event.label.name == 'invalid'
    runs-on: ubuntu-latest

    steps:
      - name: Comment on issue
        if: ${{ github.event_name == 'issues' }}
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh issue comment ${{ github.event.issue.html_url }} --body "This issue will be closed due to being marked as invalid either automatically or manually."

      - name: Comment on PR
        if: ${{ github.event_name == 'pull_request_target' }}
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr comment ${{ github.event.pull_request.html_url }} --body "This PR will be closed due to being marked as invalid either automatically or manually."

      - name: Close issue
        if: ${{ github.event_name == 'issues' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh issue close ${{ github.event.issue.html_url }}

      - name: Close PR
        if: ${{ github.event_name == 'pull_request_target' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr close ${{ github.event.pull_request.html_url }}