name: PR Validation

on:
  pull_request:

jobs: 
  Validation:
    name: Validation
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4

        - run: python3 scripts/test.py

  Close_PR:
    name: Close PR
    needs: Validation
    if: failure()
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v4

      - run: gh pr comment ${{ github.event.pull_request.html_url }} --body "This PR will be closed due to failing validation."
      - run: gh pr edit ${{ github.event.pull_request.html_url }} --add-label "invalid"

    env:
      GH_TOKEN: ${{ secrets.PAT }}

  Mark_as_Valid:
    name: Mark PR as Valid
    needs: Validation
    if: success()
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v4

      - run: gh pr merge ${{ github.event.pull_request.html_url }} --auto --squash --subject "Merge pull request(#${{ github.event.pull_request.number }})" --body "Auto merge after validation is passed."
      - run: gh pr edit ${{ github.event.pull_request.html_url }} --add-label "validation passed"

    env:
      GH_TOKEN: ${{ secrets.PAT }}